services:
  telegram-service-postgres:
    image: postgres:15-alpine
    container_name: telegram-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_service
    ports:
      - '5442:5432'
    volumes:
      - telegram-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  telegram-service-redis:
    image: redis:7-alpine
    container_name: telegram-service-redis
    ports:
      - '6391:6379'
    volumes:
      - telegram-redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  telegram-postgres-data:
  telegram-redis-data:
