coverage:
  status:
    project:
      default:
        target: 50%
    patch:
      default:
        target: 50%

flags:
  users-service:
    paths:
      - apps/users-service/
    carryforward: true
  chat-service:
    paths:
      - apps/chat-service/
    carryforward: true
  file-service:
    paths:
      - apps/file-service/
    carryforward: true
  main-service:
    paths:
      - apps/main-service/
    carryforward: true
  billing-service:
    paths:
      - apps/billing-service/
    carryforward: true
  notification-service:
    paths:
      - apps/notification-service/
    carryforward: true
  telegram-service:
    paths:
      - apps/telegram-service/
    carryforward: true
  core:
    paths:
      - libs/core/
    carryforward: true
  shared-kernel:
    paths:
      - libs/shared-kernel/
    carryforward: true

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
