apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flexobo-infra

resources:
  - namespace.yaml
  - infisical-secrets.yaml
  - infisical-mongo.yaml
  - infisical-redis.yaml
  - infisical.yaml
  - infisical-operator.yaml
  - rabbitmq.yaml

commonLabels:
  app.kubernetes.io/part-of: flexobo-infrastructure
