apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: flexobo
  labels:
    app: users-service
spec:
  type: ClusterIP
  ports:
    - port: 3005
      targetPort: 3005
      name: http
    - port: 50052
      targetPort: 50052
      name: grpc
  selector:
    app: users-service
