apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: admin-panel

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: admin-panel
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 20
    target:
      kind: HorizontalPodAutoscaler
      name: admin-panel-hpa

configMapGenerator:
  - name: admin-panel-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
