apiVersion: v1
kind: Service
metadata:
  name: main-service
  namespace: flexobo
  labels:
    app: main-service
spec:
  type: ClusterIP
  ports:
    - port: 3008
      targetPort: 3008
      name: http
  selector:
    app: main-service
