export enum SubscriptionStatus {
  TRIALING = 'TRIALING',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum BillingCycle {
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentProvider {
  STRIPE = 'STRIPE',
  CLICK = 'CLICK',
}

export enum PaymentType {
  SUBSCRIPTION = 'SUBSCRIPTION',
  ONE_TIME = 'ONE_TIME',
  REFUND = 'REFUND',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  PAID = 'PAID',
  VOID = 'VOID',
  UNCOLLECTIBLE = 'UNCOLLECTIBLE',
}

export enum UsageType {
  LOAD_CREATED = 'LOAD_CREATED',
  TRIP_POSTED = 'TRIP_POSTED',
  BID_PLACED = 'BID_PLACED',
  BOOKING_CREATED = 'BOOKING_CREATED',
  TEAM_MEMBER_ADDED = 'TEAM_MEMBER_ADDED',
  FILE_UPLOADED = 'FILE_UPLOADED',
}

export enum PlanFeature {
  ANALYTICS = 'ANALYTICS',
  PRIORITY_SUPPORT = 'PRIORITY_SUPPORT',
  API_ACCESS = 'API_ACCESS',
  CUSTOM_BRANDING = 'CUSTOM_BRANDING',
  ADVANCED_SEARCH = 'ADVANCED_SEARCH',
  BULK_OPERATIONS = 'BULK_OPERATIONS',
  EXPORT_DATA = 'EXPORT_DATA',
  WEBHOOKS = 'WEBHOOKS',
  SSO = 'SSO',
  DEDICATED_SUPPORT = 'DEDICATED_SUPPORT',
}

export enum AggregateType {
  PLAN = 'PLAN',
  SUBSCRIPTION = 'SUBSCRIPTION',
  PAYMENT = 'PAYMENT',
  INVOICE = 'INVOICE',
}
