apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-service
data:
  NODE_ENV: "production"
  ORDER_SERVICE_PORT: "3000"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis-order"
  REDIS_PORT: "6379"
  OTEL_SERVICE_NAME: "order-service"
