apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flexobo-dev

bases:
  - ../../base

nameSuffix: -dev

commonLabels:
  environment: development

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: order-service
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: admin-panel

configMapGenerator:
  - name: flexobo-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - NODE_ENV=development
