apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flexobo-ingress
  namespace: flexobo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.flexobo.com
        - admin.flexobo.com
      secretName: flexobo-tls
  rules:
    - host: api.flexobo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
    - host: admin.flexobo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-panel
                port:
                  number: 3002
