apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flexobo

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - redis.yaml
  - order-service.yaml
  - api-gateway.yaml
  - admin-panel.yaml
  - ingress.yaml
  - pdb.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: flexobo
  app.kubernetes.io/managed-by: kustomize
