apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-panel-config
  namespace: admin-panel
data:
  NODE_ENV: "production"
  ADMIN_PANEL_PORT: "3002"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis-admin"
  REDIS_PORT: "6379"
  ORDER_SERVICE_URL: "http://order-service.order-service.svc.cluster.local:3000"
  GATEWAY_SERVICE_URL: "http://api-gateway.api-gateway.svc.cluster.local:3001"
  OTEL_SERVICE_NAME: "admin-panel"
