apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-panel-ingress
  namespace: admin-panel
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: admin.flexobo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-panel
                port:
                  number: 3002
