apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flexobo-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

configMapGenerator:
  - name: flexobo-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=info
